services:
  frontend:
    build:
      context: ./frontend
    container_name: se-project-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
    environment:
      - TZ=Asia/Bangkok
    env_file:
      - ./backend/.env
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    container_name: se-project-backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      - ./backend/src/uploads:/app/src/uploads
    environment:
      - TZ=Asia/Bangkok
