version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    container_name: se-project-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    container_name: se-project-backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app

